<a href="https://colab.research.google.com/github/carmeniturbe/ejercicios_DS_Fundamentals/blob/main/Ejercicio_Numpy_Panaderia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

price = [2, 1, 10]
type(price)
quantity_sold = [17, 40, 1]
type(quantity_sold)

#Encontrar el dinero recaudado para cada tipo de elemento. Queremos el precio * cantidad para cada elemento.
#Tratemos de multiplicar nuestros arrays.

price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
type(price_array)
dinero_recaudado = price_array * quantity_sold_array
print(dinero_recaudado)

#Profit: To find the profit of each item, we want to subtract the cost from the price.
#A NumPy array will perform the subtraction elementwise as shown:

cost_array = np.array([0.25, 0.50, 5.00])
profit_array = price_array - cost_array
print(profit_array)

#Supongamos que quieren identificar qué elementos obtuvieron un beneficio superior a $2 por elemento.
#Pueden usar el siguiente código para preguntar si la declaración es True (verdadera) o False (falsa) para cada elemento en el array.

profit_array > 2

#Adicion: El club también vende tartas por $7, así que debemos actualizar nuestro price_array.

price_array = np.append(price_array, 7)
print(price_array)

#Adicion: El club quiere agregar los siguientes precios:  4,50𝑝𝑜𝑟𝑑𝑢𝑙𝑐𝑒𝑠, 3 por una magdalena,  4𝑝𝑜𝑟𝑢𝑛𝑎𝑏𝑎𝑟𝑟𝑎𝑑𝑒𝑝𝑎𝑛𝑑𝑒𝑝𝑙á𝑡𝑎𝑛𝑜𝑦 9 por una torta.

price_array = np.append(price_array, [4.50, 3, 4, 9])
print(price_array)

#Eliminar y Slicing: Resulta que nadie planea hacer una torta, así que quieren eliminar el precio de ese elemento del array.

price_array = np.delete(price_array, -1) #-- Esto era lo que decía la clase
print("Arreglo de precios", price_array)

#price_array = price_array[:-1] #otra forma - (slicing)
#print(price_array)

#Reemplazar: Después el club decide subir el precio de los pasteles de  10𝑎 12.
#Nuevamente, tendremos que identificar el elemento usando el índice. Los pasteles están en el índice 2.

price_array[2] = 12
print(price_array)

#2) Actualicen el quantity_sold_array para incluir la venta de 2 tartas, 3 bandejas de dulces, 16 magdalenas y 5 panes de plátano.
#También se darán cuenta que una de las galletas que pensaron que se había vendido en realidad se cayó al suelo, así que editen quantity_sold_array de 40 a 39.

quantity_sold_array = np.append(quantity_sold_array,[2, 3, 16, 5])
print(quantity_sold_array)

#3) Determinen la cantidad de dinero recaudado de la venta de cada elemento en la venta de la panadería.

quantity_sold_array[1] = 39
print(quantity_sold_array)

total_money_each = price_array * quantity_sold_array
print(total_money_each)

#4) Creen un array de NumPy "quantity_leftover" que incluya la cantidad de cada elemento restante al final de la venta: 2 pasteles, 1 tarta, 6 bandejas de dulces, 2 panes de plátano. Pista: Asegúrense de incluir “0” de cada elemento que se haya vendido.
#¿Por qué esto es importante cuando se crea un array? R = Es importante porque cuando intenemos hacer operaciones aritmaticas entre los arrays ambos deben tener la misma cantidad de caracteres

quantity_leftover_array = np.array([0, 0, 2, 1, 6, 0, 2])

#El club decide vender los elementos restantes a mitad de precio, y todo se venda rápidamente.
#Determinen cuanto dinero se recaudó de la venta de liquidación.
quantity_sold_sale = (price_array * quantity_leftover_array) / 2
total_quantity_sold_sale = np.sum(quantity_sold_sale)
print(total_quantity_sold_sale)

#5)¿Cuánto dinero total se recaudó de la venta de panadería (incluido la venta del precio total y los elementos liquidados)?

total_income = np.sum(total_money_each)
print(total_income)

print(total_quantity_sold_sale + total_income)


[34 40 10]
[1.75 0.5  5.  ]
[ 2  1 10  7]
[ 2.   1.  10.   7.   4.5  3.   4.   9. ]
Arreglo de precios [ 2.   1.  10.   7.   4.5  3.   4. ]
[ 2.   1.  12.   7.   4.5  3.   4. ]
[17 40  1  2  3 16  5]
[17 39  1  2  3 16  5]
[34.  39.  12.  14.  13.5 48.  20. ]
33.0
180.5
213.5
